// react_fw/src/components/user-form.js
import React, {useState} from "react";
import "./user-form.scss";

const UserForm = ({unshiftUser}) => {
  const [person, setFN] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    gender: '',
  });

  const isFormValid = () => {
    if (
      !person.firstName ||
      !person.lastName ||
      !person.email ||
      !person.phone ||
      !person.gender
    ) {
      return false
    }

    return true
  }

  return (
    <div className="form-container">
      <h3>Add Person</h3>
      <form>
        <input placeholder="First name" value={person.firstName} onChange={e => setFN({...person, firstName: e.target.value})}></input>
        <input placeholder="Last name" value={person.lastName} onChange={e => setFN({...person, lastName: e.target.value})}></input>
        <input placeholder="Email" value={person.email} onChange={e => setFN({...person, email: e.target.value})}></input>
        <input placeholder="Phone" value={person.phone} onChange={e => setFN({...person, phone: e.target.value})}></input>
        <select name="gender"  value={person.gender} onChange={e => setFN({...person, gender: e.target.value})}>
          <option value="">--Please choose an option--</option>
          <option value="M">M</option>
          <option value="F">F</option>
        </select>
      </form>
      <button type="submit" onClick={() => unshiftUser(person)} disabled={!isFormValid()}>Add Person</button>
    </div>
  );
};

export default UserForm;

// angular_fw/src/app/components/user-form/user-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CoreService } from 'src/app/services/core.service';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.scss']
})
export class UserFormComponent implements OnInit {

  public form: FormGroup;

  constructor(private fb: FormBuilder, private coreService: CoreService) { }

  ngOnInit() {
    this.form = this.fb.group({
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      gender: ['', Validators.required],
      phone: ['', Validators.required],
    });
  }

  public onSubmit() {
    this.coreService.personCollection = [
      this.form.value,
      ...this.coreService.personCollection
   ];
  }

}

<div class="form-container">
  <h3>Add Person</h3>
  <form [formGroup]="form" (ngSubmit)="onSubmit()" (keydown.enter)="onSubmit()">
    <input placeholder="First name" formControlName="firstName">
    <input placeholder="Last name" formControlName="lastName">
    <input placeholder="Email" formControlName="email">
    <input placeholder="Phone" formControlName="phone">
    <select name="gender" formControlName="gender">
      <option value="">--Please choose an option--</option>
      <option value="M">M</option>
      <option value="F">F</option>
    </select>
  </form>
  <button type="submit" (click)="onSubmit()" [disabled]="!form.valid">Add Person</button>
</div>
